### ISSUE TITLE
`berks install` does not work with Nagios dependency

### ISSUE THREAD

**Issue by cbou** [sous-chefs/nrpe#117]
## :ghost: Brief Description

I try to install this cookbook with Berkshelf but it fails.

## :pancakes: Cookbook version

2.1.0

## :woman_cook:  Chef-Infra Version

Chef Infra Client: 15.0.300
Berkshelf 7.0.8

## :tophat: Platform details

Mac OS X 10.14.6

## Steps To Reproduce

I add this `Berksfile`

```
source 'https://supermarket.chef.io'

cookbook 'npre', '~> 2.1.0'
```

Then running `berks install` produces 

```
Resolving cookbook dependencies...
Fetching cookbook index from https://supermarket.chef.io...
Unable to satisfy the following requirements:

- `npre (~> 2.1.0)` required by `user-specified dependency`
Unable to find a solution for demands: npre (~> 2.1.0)
```

## :police_car: Expected behavior

I would expect the cookbook to be installed

## :heavy_plus_sign: Additional context

It worked once but since now never again.

**Comment by tas50** [comment]
Any chance you can try this again with 3.0?

**Comment by cbou** [comment]
Version `3.0.0` produces the same error.

Are you able to reproduce the error or is that something related to my local machine?

**Comment by cbou** [comment]
I got the same issue on a fresh Debian 10 virtual server.
