### ISSUE TITLE
Supermarket version "2.0.1" not working

### ISSUE THREAD

**Issue by jmauro** [sous-chefs/nrpe#70]
### Cookbook version
2.0.1

### Chef-client version
chef-12.18.31-1

### Platform Details
CentOS

### Scenario:
Just include the recipe

### Steps to Reproduce:
Just include the recipe

### Expected Result:
The template is not valid but the last commit fixed it.

Do you (@damacus & @tas50) have any windows when the latest bug fix will be released?

**Comment by shoekstra** [comment]
v2.0.2 has been pushed to the supermarket.
