### ISSUE TITLE
Windows Client Support

### ISSUE THREAD

**Issue by shoekstra** [sous-chefs/nrpe#83]
Hi,

This cookbook doesn't support Windows but we use it to create checks using `nrpe_check`.  At the moment the check doesn't work on Windows due to [this](https://github.com/sous-chefs/nrpe/blob/master/resources/check.rb#L37-L39) and [this](https://github.com/sous-chefs/nrpe/blob/master/resources/check.rb#L52-L54).

To get around this, I've copied the resource into a wrapper cookbook and named it `nrpe_check_windows`; what are the feels if we add `unless platform?('windows')` to each of the highlighted lines so this is not needed?

It wouldn't mean Windows support but it would allow people like me to reuse the resource to create checks after installing NSClient++ by whatever means.

Stephen

**Comment by damacus** [comment]
Whatever way we can get his working on Windows, I'd be happy to merge PRs in.
