### ISSUE TITLE
easy fix: tripping over new platform_family behavior in Amazon Linux

### ISSUE THREAD

**Issue by jstange** [sous-chefs/nrpe#96]
### Cookbook version
2.0.5

### Chef-client version
14.12.9

### Platform Details
Amazon Linux

### Scenario:
Default value of `node['nrpe']['plugin_dir']` is wrong with newer Chef Clients. Should be `/usr/lib64/nagios/plugins`, but comes back with `/usr/lib/nagios/plugins` now. This is because in Chef 13 or 14, Amazon Linux got its own `platform_family`, so it's no longer synonymous with `rhel`.

### Steps to Reproduce:
Try on Amazon Linux with Chef 14

Super easy to fix. In `attributes/default.rb`, if we change:

```
when 'rhel', 'fedora'
```

...to:

```
when 'rhel', 'fedora', 'amazon'
```

...we get the expected behavior.

**Comment by Xorima** [comment]
Hi @jstange 

Is there any chance you can issue a pr for this fix, if you could update the metadata as well I would appreciate it

Thanks 👍

**Comment by jstange** [comment]
Aside: The `platform_family` thing might be a change from Amazon Linux 1 to Amazon Linux 2, rather than Chef, but the result is the same either way.

**Comment by jstange** [comment]
Turns out I have an afternoon, so yeah, I can fiddle with it
